# Generated by Django 6.0.3 on 2026-03-31 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_subject_exam_subject'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examresult',
            unique_together=set(),
        ),
    ]
