# Generated by Django 6.0.3 on 2026-04-19 04:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_examresult_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examresult',
            unique_together={('user', 'exam')},
        ),
    ]
